# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/04_cache_handler.ipynb.

# %% auto 0
__all__ = ['CacheHandler']

# %% ../../nbs/04_cache_handler.ipynb 4
from typing import Optional



# %% ../../nbs/04_cache_handler.ipynb 5
class CacheHandler:
    """Callback handler for tool usage."""

    _cache: dict = {}

    def __init__(self):
        self._cache = {}

    def add(self, tool, input, output):
        input = input.strip()
        self._cache[f"{tool}-{input}"] = output

    def read(self, tool, input) -> Optional[str]:
        input = input.strip()
        return self._cache.get(f"{tool}-{input}")

