# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/langGraph_swarm',
                'doc_host': 'https://Dmaturana81.github.io',
                'git_url': 'https://github.com/Dmaturana81/langGraph_swarm',
                'lib_path': 'langGraph_swarm'},
  'syms': {'langGraph_swarm.core': {'langGraph_swarm.core.foo': ('core.html#foo', 'langGraph_swarm/core.py')}}}
